[package]
name = "closely"
version = "0.1.17"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.79"
bytes = "1.6.0"
clap = { version = "4.4.16", features = ["derive"] }
futures = "0.3.30"
headless_chrome = "1.0.9"
humantime-serde = "1.1.1"
image = "0.25.1"
itertools = "0.12.1"
once_cell = "1.19.0"
paste = "1.0.14"
rand = "0.8.5"
reqwest = { version = "0.11.23", features = ["json", "gzip", "multipart"] }
serde = { version = "1.0.195", features = ["derive", "rc"] }
serde_json = "1.0.111"
spdlog-rs = { version = "0.3.12", features = ["source-location"] }
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros", "fs", "time", "sync"] }
toml = "0.8.8"

[features]
qq = []
