[package]
name = "closely"
version = "0.1.9"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.79"
chrono = "0.4.31"
clap = { version = "4.4.16", features = ["derive"] }
const_format = "0.2.32"
headless_chrome = "1.0.9"
humantime-serde = "1.1.1"
once_cell = "1.19.0"
reqwest = { version = "0.11.23", features = ["json", "gzip"] }
scraper = "0.18.1"
serde = { version = "1.0.195", features = ["derive", "rc"] }
serde_json = "1.0.111"
spdlog-rs = "0.3.12"
tap = "1.0.1"
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros", "fs", "time", "sync"] }
toml = "0.8.8"
